// Auto-generated by deepguard testgen — 2026-07-10T20:05:31+03:30
// Source: express-complex.js

// --- anonymous (line 16) ---
const requestHandler = require('./express-complex');
const pool = require('./database');

jest.mock('./database');

describe('Request Handler Tests', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  test('Happy path: Valid inputs', async () => {
    const req = { query: { q: 'test', category: 'electronics', min_price: 100, max_price: 500 } };
    const res = { json: jest.fn() };
    const mockProducts = [{ id: 1, name: 'test product', price: 150 }];

    pool.query.mockResolvedValueOnce([mockProducts]);
    await requestHandler(req, res);

    expect(pool.query).toHaveBeenCalledWith(
      expect.stringContaining("SELECT * FROM products WHERE 1=1 AND name LIKE '%test%' AND category = 'electronics' AND price >= 100 AND price <= 500")
    );
    expect(res.json).toHaveBeenCalledWith(mockProducts);
  });

  test('SQL Injection: Injected payload', async () => {
    const req = { query: { q: 'anything; DROP TABLE products;', category: null, min_price: null, max_price: null } };
    const res = { json: jest.fn() };
    
    pool.query.mockResolvedValueOnce([[]]);
    await requestHandler(req, res);

    expect(pool.query).toHaveBeenCalledWith(
      expect.stringContaining("SELECT * FROM products WHERE 1=1 AND name LIKE '%anything; DROP TABLE products;%' AND category = NULL")
    );
  });

  test('Path Traversal: Malicious file path input', async () => {
    const req = { query: { q: '../etc/passwd', category: null, min_price: null, max_price: null } };
    const res = { json: jest.fn() };

    pool.query.mockResolvedValueOnce([[]]);
    await requestHandler(req, res);

    expect(pool.query).toHaveBeenCalledWith(
      expect.stringContaining("SELECT * FROM products WHERE 1=1 AND name LIKE '%../etc/passwd%' AND category = NULL")
    );
  });

  test('Oversized input: Very long search term', async () => {
    const longInput = 'A'.repeat(10000);
    const req = { query: { q: longInput, category: null, min_price: null, max_price: null } };
    const res = { json: jest.fn() };

    pool.query.mockResolvedValueOnce([[]]);
    await requestHandler(req, res);

    expect(pool.query).toHaveBeenCalledWith(
      expect.stringContaining(`name LIKE '%${longInput}%'`)
    );
  });

  test('Null inputs: Should handle null gracefully', async () => {
    const req = { query: { q: null, category: null, min_price: null, max_price: null } };
    const res = { json: jest.fn() };

    pool.query.mockResolvedValueOnce([[]]);
    await requestHandler(req, res);

    expect(pool.query).toHaveBeenCalledWith(
      expect.stringContaining("SELECT * FROM products WHERE 1=1")
    );
  });

  test('Integer boundary values: minPrice 0, maxPrice MAX_INT', async () => {
    const req = { query: { q: null, category: null, min_price: 0, max_price: 2147483647 } };
    const res = { json: jest.fn() };

    const mockProducts = [{ id: 1, name: 'sample', price: 0 }];
    pool.query.mockResolvedValueOnce([mockProducts]);
    await requestHandler(req, res);

    expect(pool.query).toHaveBeenCalledWith(
      expect.stringContaining("SELECT * FROM products WHERE 1=1 AND price >= 0 AND price <= 2147483647")
    );
    expect(res.json).toHaveBeenCalledWith(mockProducts);
  });

  test('Boundary Value: minPrice -1', async () => {
    const req = { query: { q: null, category: null, min_price: -1, max_price: null } };
    const res = { json: jest.fn() };

    pool.query.mockResolvedValueOnce([[]]);
    await requestHandler(req, res);

    expect(pool.query).toHaveBeenCalledWith(
      expect.stringContaining("SELECT * FROM products WHERE 1=1 AND price >= -1")
    );
  });
});

// --- anonymous (line 48) ---
const express = require('express');
const request = require('supertest');
const app = express();
const pool = { query: jest.fn() }; // Mocking the database query

app.get('/:table', async (req, res) => {
  const tableName = req.params.table;
  const year = req.query.year;
  
  const query = `SELECT * FROM ${tableName} WHERE year = ${year}`;
  
  try {
    const [rows] = await pool.query(query);
    res.json({ table: tableName, data: rows });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

describe('GET /:table', () => {
  it('should return data for valid inputs', async () => {
    const mockData = [{ id: 1, name: 'example' }];
    pool.query.mockResolvedValue([mockData]);
    const response = await request(app).get('/validTable?year=2023');
    expect(response.status).toBe(200);
    expect(response.body).toEqual({ table: 'validTable', data: mockData });
  });
  
  it('should handle SQL injection payloads', async () => {
    const injectionPayload = "'; DROP TABLE users; --";
    pool.query.mockResolvedValue([[]]);
    const response = await request(app).get(`/validTable?year=${injectionPayload}`);
    expect(response.status).toBe(200);
    expect(pool.query).toHaveBeenCalledWith(`SELECT * FROM validTable WHERE year = '${injectionPayload}'`);
  });
  
  it('should handle path traversal attempts', async () => {
    const pathTraversal = '../etc/passwd';
    pool.query.mockResolvedValue([[]]);
    const response = await request(app).get(`/${pathTraversal}?year=2023`);
    expect(response.status).toBe(200);
    expect(pool.query).toHaveBeenCalledWith(`SELECT * FROM ${pathTraversal} WHERE year = 2023`);
  });
  
  it('should handle oversized input', async () => {
    const oversized = 'a'.repeat(10000);
    pool.query.mockResolvedValue([[]]);
    const response = await request(app).get(`/${oversized}?year=2023`);
    expect(response.status).toBe(200);
  });
  
  it('should handle null year input', async () => {
    const response = await request(app).get('/validTable?year=');
    expect(response.status).toBe(200);
  });
  
  it('should handle boundary values for year', async () => {
    const boundaryValues = [0, -1, Number.MAX_SAFE_INTEGER];
    for (const year of boundaryValues) {
      pool.query.mockResolvedValue([[]]);
      const response = await request(app).get(`/validTable?year=${year}`);
      expect(response.status).toBe(200);
    }
  });
});

// --- anonymous (line 77) ---
const express = require('express');
const request = require('supertest');
const { pool } = require('./db'); // Mock your database pool

const app = express();

app.get('/products', async (req, res) => {
  const filterExpr = req.query.filter; // e.g., "price > 100 AND category = 'electronics'"

  const query = `SELECT * FROM products WHERE ${filterExpr}`;
  
  try {
    const [rows] = await pool.query(query);
    res.json(rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

describe('GET /products', () => {
  beforeAll(() => {
    jest.spyOn(pool, 'query'); // Mock pool query method
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  test('happy path: valid filter', async () => {
    const mockData = [{ id: 1, price: 150, category: 'electronics' }];
    pool.query.mockResolvedValue([mockData]);

    const response = await request(app)
      .get('/products?filter=price > 100 AND category = \'electronics\'');

    expect(response.status).toBe(200);
    expect(response.body).toEqual(mockData);
  });

  test('SQL Injection', async () => {
    const maliciousInput = "1; DROP TABLE products;";
    pool.query.mockResolvedValue([]);

    const response = await request(app)
      .get(`/products?filter=${encodeURIComponent(maliciousInput)}`);

    expect(pool.query).toHaveBeenCalledWith(`SELECT * FROM products WHERE ${maliciousInput}`);
    expect(response.status).toBe(500);
    expect(response.body).toHaveProperty('error');
  });

  test('Path Traversal', async () => {
    const maliciousPath = "../etc/passwd";
    pool.query.mockResolvedValue([]);

    const response = await request(app)
      .get(`/products?filter=${encodeURIComponent(maliciousPath)}`);

    expect(pool.query).toHaveBeenCalledWith(`SELECT * FROM products WHERE ${maliciousPath}`);
    expect(response.status).toBe(500);
    expect(response.body).toHaveProperty('error');
  });

  test('Oversized input', async () => {
    const oversizedInput = 'a'.repeat(10000);
    pool.query.mockResolvedValue([]);

    const response = await request(app)
      .get(`/products?filter=${encodeURIComponent(oversizedInput)}`);

    expect(pool.query).toHaveBeenCalledWith(`SELECT * FROM products WHERE ${oversizedInput}`);
    expect(response.status).toBe(500);
    expect(response.body).toHaveProperty('error');
  });

  test('Integer boundary values', async () => {
    const boundTestInputs = [0, -1, Number.MAX_SAFE_INTEGER];
    for (const input of boundTestInputs) {
      pool.query.mockResolvedValue([]);
      const response = await request(app)
        .get(`/products?filter=price = ${input}`);

      expect(pool.query).toHaveBeenCalledWith(`SELECT * FROM products WHERE price = ${input}`);
      expect(response.status).toBe(200); // Assuming valid integers return 200.
    }
  });
});

// --- anonymous (line 90) ---
const request = require('supertest');
const express = require('express');

const app = express();

app.get('/test', (req, res) => {
  res.send('Hello, World!');
});

describe('GET /test', () => {
  it('should return Hello, World! for valid request', async () => {
    const response = await request(app).get('/test');
    expect(response.status).toBe(200);
    expect(response.text).toBe('Hello, World!');
  });

  it('should handle SQL injection attempts gracefully', async () => {
    const sqlInjectionPayload = "'; DROP TABLE users; --";
    const response = await request(app).get(`/test?input=${encodeURIComponent(sqlInjectionPayload)}`);
    expect(response.status).toBe(200);
    expect(response.text).toBe('Hello, World!');
  });

  it('should handle path traversal attempts gracefully', async () => {
    const pathTraversalPayload = "../../etc/passwd";
    const response = await request(app).get(`/test?file=${encodeURIComponent(pathTraversalPayload)}`);
    expect(response.status).toBe(200);
    expect(response.text).toBe('Hello, World!');
  });

  it('should return 400 for oversized input', async () => {
    const oversizedInput = 'a'.repeat(10001); // Over 10,000 characters
    const response = await request(app).get(`/test?input=${encodeURIComponent(oversizedInput)}`);
    expect(response.status).toBe(400);
  });

  it('should handle integer boundary values', async () => {
    const boundaryInputs = [0, -1, Number.MAX_SAFE_INTEGER];
    for (const input of boundaryInputs) {
      const response = await request(app).get(`/test?number=${input}`);
      expect(response.status).toBe(200);
      expect(response.text).toBe('Hello, World!');
    }
  });

  it('should return 400 for null input', async () => {
    const response = await request(app).get('/test?input=null');
    expect(response.status).toBe(400);
  });
});

