// Auto-generated by deepguard testgen — 2026-07-10T20:07:57+03:30
// Source: prisma-service.js

// --- getUserById (line 9) ---
import { getUserById } from './prisma-service';
import { prisma } from './prisma-client';

jest.mock('./prisma-client');

describe('getUserById', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('should return user for valid userId', async () => {
    const userId = 1;
    const mockUser = { id: userId, name: 'John Doe' };
    prisma.$queryRaw.mockResolvedValue(mockUser);

    const result = await getUserById(userId);
    expect(result).toEqual(mockUser);
    expect(prisma.$queryRaw).toHaveBeenCalledWith(expect.anything());
  });

  it('should handle SQL injection payload', async () => {
    const userId = "1; DROP TABLE users;";
    prisma.$queryRaw.mockResolvedValue(null);

    const result = await getUserById(userId);
    expect(result).toBeNull();
    expect(prisma.$queryRaw).toHaveBeenCalledWith(expect.anything());
  });

  it('should handle path traversal strings', async () => {
    const userId = "../etc/passwd";
    prisma.$queryRaw.mockResolvedValue(null);

    const result = await getUserById(userId);
    expect(result).toBeNull();
    expect(prisma.$queryRaw).toHaveBeenCalledWith(expect.anything());
  });

  it('should handle oversized input', async () => {
    const userId = '1'.repeat(1000);
    prisma.$queryRaw.mockResolvedValue(null);

    const result = await getUserById(userId);
    expect(result).toBeNull();
    expect(prisma.$queryRaw).toHaveBeenCalledWith(expect.anything());
  });

  it('should handle null input', async () => {
    const userId = null;
    prisma.$queryRaw.mockResolvedValue(null);

    const result = await getUserById(userId);
    expect(result).toBeNull();
    expect(prisma.$queryRaw).toHaveBeenCalledWith(expect.anything());
  });

  it('should handle integer boundary value 0', async () => {
    const userId = 0;
    const mockUser = { id: userId, name: 'Boundary User' };
    prisma.$queryRaw.mockResolvedValue(mockUser);

    const result = await getUserById(userId);
    expect(result).toEqual(mockUser);
    expect(prisma.$queryRaw).toHaveBeenCalledWith(expect.anything());
  });

  it('should handle integer boundary value -1', async () => {
    const userId = -1;
    const mockUser = { id: userId, name: 'Negative User' };
    prisma.$queryRaw.mockResolvedValue(mockUser);

    const result = await getUserById(userId);
    expect(result).toEqual(mockUser);
    expect(prisma.$queryRaw).toHaveBeenCalledWith(expect.anything());
  });

  it('should handle integer boundary value MAX_INT', async () => {
    const userId = Number.MAX_SAFE_INTEGER;
    const mockUser = { id: userId, name: 'Max Int User' };
    prisma.$queryRaw.mockResolvedValue(mockUser);

    const result = await getUserById(userId);
    expect(result).toEqual(mockUser);
    expect(prisma.$queryRaw).toHaveBeenCalledWith(expect.anything());
  });
});

// --- updateUserEmail (line 14) ---
const prisma = require('../prisma-service');

jest.mock('../prisma-service');

describe('updateUserEmail', () => {
  const validUserId = 1;
  const validEmail = 'test@example.com';

  beforeEach(() => {
    prisma.$executeRaw.mockClear();
  });

  test('should update user email with valid inputs', async () => {
    prisma.$executeRaw.mockResolvedValueOnce({ affectedRows: 1 });

    const result = await prisma.updateUserEmail(validUserId, validEmail);
    expect(prisma.$executeRaw).toHaveBeenCalledWith(expect.stringContaining('UPDATE users SET email ='));
    expect(result).toEqual({ affectedRows: 1 });
  });

  test('should handle SQL injection', async () => {
    const sqlInjectionEmail = "' OR '1'='1";
    prisma.$executeRaw.mockResolvedValueOnce({ affectedRows: 0 });

    const result = await prisma.updateUserEmail(validUserId, sqlInjectionEmail);
    expect(prisma.$executeRaw).toHaveBeenCalledWith(expect.stringContaining('UPDATE users SET email ='));
    expect(result).toEqual({ affectedRows: 0 });
  });

  test('should handle path traversal strings', async () => {
    const pathTraversalEmail = "../../etc/passwd";
    prisma.$executeRaw.mockResolvedValueOnce({ affectedRows: 0 });

    const result = await prisma.updateUserEmail(validUserId, pathTraversalEmail);
    expect(prisma.$executeRaw).toHaveBeenCalledWith(expect.stringContaining('UPDATE users SET email ='));
    expect(result).toEqual({ affectedRows: 0 });
  });

  test('should handle oversized input', async () => {
    const oversizedEmail = 'a'.repeat(256); // Assuming max length is 255 for email
    prisma.$executeRaw.mockResolvedValueOnce({ affectedRows: 1 });

    const result = await prisma.updateUserEmail(validUserId, oversizedEmail);
    expect(prisma.$executeRaw).toHaveBeenCalledWith(expect.stringContaining('UPDATE users SET email ='));
    expect(result).toEqual({ affectedRows: 1 });
  });

  test('should handle null email input', async () => {
    const nullEmail = null;
    prisma.$executeRaw.mockResolvedValueOnce({ affectedRows: 0 });

    const result = await prisma.updateUserEmail(validUserId, nullEmail);
    expect(prisma.$executeRaw).toHaveBeenCalledWith(expect.stringContaining('UPDATE users SET email ='));
    expect(result).toEqual({ affectedRows: 0 });
  });

  test('should handle integer boundary values', async () => {
    const maxIntUserId = Number.MAX_SAFE_INTEGER;
    prisma.$executeRaw.mockResolvedValueOnce({ affectedRows: 1 });

    const result = await prisma.updateUserEmail(maxIntUserId, validEmail);
    expect(prisma.$executeRaw).toHaveBeenCalledWith(expect.stringContaining('UPDATE users SET email ='));
    expect(result).toEqual({ affectedRows: 1 });
  });

  test('should handle negative userId', async () => {
    const negativeUserId = -1;
    prisma.$executeRaw.mockResolvedValueOnce({ affectedRows: 0 });

    const result = await prisma.updateUserEmail(negativeUserId, validEmail);
    expect(prisma.$executeRaw).toHaveBeenCalledWith(expect.stringContaining('UPDATE users SET email ='));
    expect(result).toEqual({ affectedRows: 0 });
  });
});

// --- searchUsers (line 19) ---
const prisma = require('@prisma/client');
const { searchUsers } = require('./prisma-service');

jest.mock('@prisma/client');

describe('searchUsers', () => {
  afterEach(() => {
    jest.clearAllMocks();
  });

  it('should return users for valid inputs', async () => {
    const mockUsers = [{ id: 1, name: 'John Doe' }];
    prisma.$queryRawUnsafe.mockResolvedValue(mockUsers);

    const result = await searchUsers('name', 'John Doe');
    expect(result).toEqual(mockUsers);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith("SELECT * FROM users WHERE name = 'John Doe'");
  });

  it('should handle SQL injection payloads', async () => {
    const sqlInjection = "'; DROP TABLE users; --";
    prisma.$queryRawUnsafe.mockResolvedValue([]);

    const result = await searchUsers('name', sqlInjection);
    expect(result).toEqual([]);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM users WHERE name = '${sqlInjection}'`);
  });

  it('should handle path traversal strings', async () => {
    const pathTraversal = "../../etc/passwd";
    prisma.$queryRawUnsafe.mockResolvedValue([]);

    const result = await searchUsers('filePath', pathTraversal);
    expect(result).toEqual([]);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM users WHERE filePath = '${pathTraversal}'`);
  });

  it('should handle oversized input', async () => {
    const oversizedString = 'A'.repeat(10000);
    prisma.$queryRawUnsafe.mockResolvedValue([]);

    const result = await searchUsers('name', oversizedString);
    expect(result).toEqual([]);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM users WHERE name = '${oversizedString}'`);
  });

  it('should handle null input', async () => {
    prisma.$queryRawUnsafe.mockResolvedValue([]);

    const result = await searchUsers('name', null);
    expect(result).toEqual([]);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM users WHERE name = 'null'`);
  });

  it('should handle integer boundary values', async () => {
    const boundaryValue = -1;
    prisma.$queryRawUnsafe.mockResolvedValue([]);

    const result = await searchUsers('id', boundaryValue);
    expect(result).toEqual([]);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM users WHERE id = '${boundaryValue}'`);
    
    const maxIntValue = Number.MAX_SAFE_INTEGER;
    const resultMaxInt = await searchUsers('id', maxIntValue);
    expect(resultMaxInt).toEqual([]);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM users WHERE id = '${maxIntValue}'`);
  });
});

// --- getFilteredUsers (line 25) ---
import prisma from '../path/to/prisma-client';

jest.mock('../path/to/prisma-client');

import { getFilteredUsers } from './prisma-service';

describe('getFilteredUsers', () => {
  it('should return users for valid inputs', async () => {
    prisma.$queryRawUnsafe.mockResolvedValue([{ id: 1, age: 25, country: 'USA' }]);
    const result = await getFilteredUsers(20, 30, 'USA');
    expect(result).toEqual([{ id: 1, age: 25, country: 'USA' }]);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith('SELECT * FROM users WHERE age >= 20 AND age <= 30 AND country = 'USA'');
  });

  it('should handle SQL injection payload', async () => {
    const sqlInjection = "1; DROP TABLE users; --";
    prisma.$queryRawUnsafe.mockResolvedValue([]);
    const result = await getFilteredUsers(20, 30, sqlInjection);
    expect(result).toEqual([]);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM users WHERE age >= 20 AND age <= 30 AND country = '${sqlInjection}'`);
  });

  it('should handle path traversal strings', async () => {
    const pathTraversal = "../etc/passwd";
    prisma.$queryRawUnsafe.mockResolvedValue([]);
    const result = await getFilteredUsers(20, 30, pathTraversal);
    expect(result).toEqual([]);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM users WHERE age >= 20 AND age <= 30 AND country = '${pathTraversal}'`);
  });

  it('should handle oversized input', async () => {
    const oversizedCountry = 'A'.repeat(10000);
    prisma.$queryRawUnsafe.mockResolvedValue([]);
    const result = await getFilteredUsers(20, 30, oversizedCountry);
    expect(result).toEqual([]);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM users WHERE age >= 20 AND age <= 30 AND country = '${oversizedCountry}'`);
  });

  it('should handle null inputs', async () => {
    prisma.$queryRawUnsafe.mockResolvedValue([]);
    const result = await getFilteredUsers(null, null, null);
    expect(result).toEqual([]);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith('SELECT * FROM users WHERE age >= null');
  });

  it('should handle integer boundary values', async () => {
    prisma.$queryRawUnsafe.mockResolvedValue([]);
    const resultZero = await getFilteredUsers(0, 0, 'USA');
    expect(resultZero).toEqual([]);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM users WHERE age >= 0 AND age <= 0 AND country = 'USA'`);

    const resultNegative = await getFilteredUsers(-1, -1, 'USA');
    expect(resultNegative).toEqual([]);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM users WHERE age >= -1 AND age <= -1 AND country = 'USA'`);

    const maxInt = Number.MAX_SAFE_INTEGER;
    prisma.$queryRawUnsafe.mockResolvedValue([]);
    const resultMaxInt = await getFilteredUsers(maxInt, maxInt, 'USA');
    expect(resultMaxInt).toEqual([]);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM users WHERE age >= ${maxInt} AND age <= ${maxInt} AND country = 'USA'`);
  });
});

// --- processOrder (line 40) ---
const { processOrder } = require('./prisma-service');
const prisma = require('@prisma/client');

jest.mock('@prisma/client', () => ({
  $transaction: jest.fn(),
  $executeRawUnsafe: jest.fn(),
  $queryRawUnsafe: jest.fn(),
}));

describe('processOrder', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('should update order status and return order details for valid inputs', async () => {
    const orderId = 1;
    const status = 'shipped';
    const mockOrder = [{ id: 1, status: 'shipped' }];

    prisma.$transaction.mockImplementation(async (callback) => await callback({
      $executeRawUnsafe: prisma.$executeRawUnsafe,
      $queryRawUnsafe: prisma.$queryRawUnsafe,
    }));
    prisma.$executeRawUnsafe.mockResolvedValueOnce(null);
    prisma.$queryRawUnsafe.mockResolvedValueOnce(mockOrder);

    const result = await processOrder(orderId, status);
    expect(result).toEqual(mockOrder);
    expect(prisma.$executeRawUnsafe).toHaveBeenCalledWith(`UPDATE orders SET status = 'shipped' WHERE id = 1`);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM orders WHERE id = 1`);
  });

  it('should handle SQL injection attempts in status', async () => {
    const orderId = 1;
    const status = "'); DROP TABLE orders; --";
    prisma.$transaction.mockImplementation(async (callback) => await callback({
      $executeRawUnsafe: prisma.$executeRawUnsafe,
      $queryRawUnsafe: prisma.$queryRawUnsafe,
    }));
    prisma.$executeRawUnsafe.mockResolvedValueOnce(null);

    await expect(processOrder(orderId, status)).rejects.toThrow();
    expect(prisma.$executeRawUnsafe).toHaveBeenCalledWith(`UPDATE orders SET status = '\'); DROP TABLE orders; --' WHERE id = 1`);
  });

  it('should handle path traversal in orderId', async () => {
    const orderId = '../etc/passwd';
    const status = 'shipped';
    await expect(processOrder(orderId, status)).rejects.toThrow();
  });

  it('should handle oversized input for status', async () => {
    const orderId = 1;
    const status = 'a'.repeat(10001);
    await expect(processOrder(orderId, status)).rejects.toThrow();
  });

  it('should handle integer boundary values', async () => {
    const negativeOrderId = -1;
    const maxIntOrderId = Number.MAX_SAFE_INTEGER;
    const status = 'pending';

    await expect(processOrder(negativeOrderId, status)).rejects.toThrow();
    await expect(processOrder(maxIntOrderId, status)).resolves.not.toThrow();
  });
});

// --- getOrdersSorted (line 50) ---
const prisma = require('@prisma/client');
const { getOrdersSorted } = require('./prisma-service');

jest.mock('@prisma/client', () => ({
  $queryRawUnsafe: jest.fn(),
}));

describe('getOrdersSorted', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('should return sorted orders for valid inputs', async () => {
    const mockOrders = [{ id: 1, name: 'Order 1' }, { id: 2, name: 'Order 2' }];
    prisma.$queryRawUnsafe.mockResolvedValue(mockOrders);

    const result = await getOrdersSorted('name', 'ASC');
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith('SELECT * FROM orders ORDER BY name ASC');
    expect(result).toEqual(mockOrders);
  });

  it('should handle SQL injection payloads', async () => {
    const maliciousSortField = 'name; DROP TABLE orders; --';
    prisma.$queryRawUnsafe.mockResolvedValue([]);

    const result = await getOrdersSorted(maliciousSortField, 'ASC');
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM orders ORDER BY ${maliciousSortField} ASC`);
    expect(result).toEqual([]);
  });

  it('should handle path traversal strings', async () => {
    const maliciousSortField = '../etc/passwd';
    prisma.$queryRawUnsafe.mockResolvedValue([]);

    const result = await getOrdersSorted(maliciousSortField, 'ASC');
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM orders ORDER BY ${maliciousSortField} ASC`);
    expect(result).toEqual([]);
  });

  it('should handle oversized inputs', async () => {
    const oversizedSortField = 'a'.repeat(1000); // Exceeding typical limits
    prisma.$queryRawUnsafe.mockResolvedValue([]);

    const result = await getOrdersSorted(oversizedSortField, 'ASC');
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM orders ORDER BY ${oversizedSortField} ASC`);
    expect(result).toEqual([]);
  });

  it('should handle boundary values for integer inputs', async () => {
    const maxIntSortField = Number.MAX_SAFE_INTEGER;
    prisma.$queryRawUnsafe.mockResolvedValue([]);

    const result = await getOrdersSorted(maxIntSortField.toString(), 'ASC');
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM orders ORDER BY ${maxIntSortField} ASC`);
    expect(result).toEqual([]);
  });
});

