// Auto-generated by deepguard testgen — 2026-07-10T20:08:52+03:30
// Source: prisma-unsafe.js

// --- getUsersByRole (line 8) ---
const prisma = require('@prisma/client');
const { getUsersByRole } = require('./prisma-unsafe');

jest.mock('@prisma/client', () => ({
  $queryRaw: jest.fn(),
}));

describe('getUsersByRole', () => {
  beforeEach(() => {
    prisma.$queryRaw.mockClear();
  });

  test('should return users for valid role', async () => {
    const mockResponse = [{ id: 1, role: 'admin' }, { id: 2, role: 'user' }];
    prisma.$queryRaw.mockResolvedValue(mockResponse);
    const result = await getUsersByRole('admin');
    expect(result).toEqual(mockResponse);
    expect(prisma.$queryRaw).toHaveBeenCalledWith(expect.any(String));
  });

  test('should not execute SQL injection', async () => {
    const sqlInjectionRole = 'admin; DROP TABLE users;';
    prisma.$queryRaw.mockResolvedValue([]);
    const result = await getUsersByRole(sqlInjectionRole);
    expect(result).toEqual([]);
    expect(prisma.$queryRaw).toHaveBeenCalledWith(expect.any(String));
  });

  test('should handle oversized input', async () => {
    const oversizedRole = 'a'.repeat(1000);
    prisma.$queryRaw.mockResolvedValue([]);
    const result = await getUsersByRole(oversizedRole);
    expect(result).toEqual([]);
    expect(prisma.$queryRaw).toHaveBeenCalledWith(expect.any(String));
  });

  test('should handle null input', async () => {
    prisma.$queryRaw.mockResolvedValue([]);
    const result = await getUsersByRole(null);
    expect(result).toEqual([]);
    expect(prisma.$queryRaw).toHaveBeenCalledWith(expect.any(String));
  });

  test('should not allow invalid role with path traversal', async () => {
    const pathTraversalRole = '../etc/passwd';
    prisma.$queryRaw.mockResolvedValue([]);
    const result = await getUsersByRole(pathTraversalRole);
    expect(result).toEqual([]);
    expect(prisma.$queryRaw).toHaveBeenCalledWith(expect.any(String));
  });

  test('should handle integer boundary values', async () => {
    const boundaryRoles = [0, -1, Number.MAX_SAFE_INTEGER];
    for (let i = 0; i < boundaryRoles.length; i++) {
      prisma.$queryRaw.mockResolvedValue([]);
      const result = await getUsersByRole(boundaryRoles[i].toString());
      expect(result).toEqual([]);
      expect(prisma.$queryRaw).toHaveBeenCalledWith(expect.any(String));
    }
  });
});

// --- getUserWithOrders (line 12) ---
const prisma = require('@prisma/client');

jest.mock('@prisma/client', () => {
  return {
    PrismaClient: jest.fn().mockImplementation(() => {
      return {
        $queryRawUnsafe: jest.fn(),
      };
    }),
  };
});

const { PrismaClient } = require('@prisma/client');
const db = new PrismaClient();

async function getUserWithOrders(userId) {
  const query = `
    SELECT u.*, o.*
    FROM users u
    LEFT JOIN orders o ON u.id = o.user_id
    WHERE u.id = ${userId}
  `;
  return await db.$queryRawUnsafe(query);
}

describe('getUserWithOrders', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  test('should return user with orders for valid userId', async () => {
    const mockUser = { id: 1, name: 'John Doe', orders: [] };
    const mockOrders = [{ id: 1, user_id: 1, product: 'Item 1' }];
    db.$queryRawUnsafe.mockResolvedValueOnce({ user: mockUser, orders: mockOrders });

    const result = await getUserWithOrders(1);
    expect(result).toEqual({ user: mockUser, orders: mockOrders });
    expect(db.$queryRawUnsafe).toHaveBeenCalledWith(expect.stringContaining('WHERE u.id = 1'));
  });

  test('should handle SQL injection payloads', async () => {
    const maliciousInput = "1 OR 1=1";
    db.$queryRawUnsafe.mockResolvedValueOnce([]);

    const result = await getUserWithOrders(maliciousInput);
    expect(result).toEqual([]);
    expect(db.$queryRawUnsafe).toHaveBeenCalledWith(expect.stringContaining('WHERE u.id = 1 OR 1=1'));
  });

  test('should handle path traversal strings', async () => {
    const maliciousPath = "../../etc/passwd";
    db.$queryRawUnsafe.mockResolvedValueOnce([]);

    const result = await getUserWithOrders(maliciousPath);
    expect(result).toEqual([]);
    expect(db.$queryRawUnsafe).toHaveBeenCalledWith(expect.stringContaining('WHERE u.id = ../../etc/passwd'));
  });

  test('should handle oversized inputs', async () => {
    const oversizedInput = '1'.repeat(10000);
    db.$queryRawUnsafe.mockResolvedValueOnce([]);

    const result = await getUserWithOrders(oversizedInput);
    expect(result).toEqual([]);
    expect(db.$queryRawUnsafe).toHaveBeenCalledWith(expect.stringContaining(oversizedInput));
  });

  test('should handle integer boundary values', async () => {
    const mockUser = { id: 0, name: 'Boundary User', orders: [] };
    db.$queryRawUnsafe.mockResolvedValueOnce({ user: mockUser, orders: [] });

    const result = await getUserWithOrders(0);
    expect(result).toEqual({ user: mockUser, orders: [] });
    expect(db.$queryRawUnsafe).toHaveBeenCalledWith(expect.stringContaining('WHERE u.id = 0'));

    db.$queryRawUnsafe.mockResolvedValueOnce([]);
    const resultNegative = await getUserWithOrders(-1);
    expect(resultNegative).toEqual([]);
    expect(db.$queryRawUnsafe).toHaveBeenCalledWith(expect.stringContaining('WHERE u.id = -1'));
  });
});

// --- getRecordsByTable (line 22) ---
const prisma = require('@prisma/client');
const { getRecordsByTable } = require('./prisma-unsafe');

jest.mock('@prisma/client');

describe('getRecordsByTable', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  test('happy path: valid inputs return expected records', async () => {
    const mockRecords = [{ id: 1, status: 'active', created_at: '2023-01-01' }];
    prisma.$queryRawUnsafe.mockResolvedValue(mockRecords);
    const result = await getRecordsByTable('my_table', { status: 'active', date: '2023-01-01' });
    expect(result).toEqual(mockRecords);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith("SELECT * FROM my_table WHERE 1=1 AND status = 'active' AND created_at >= '2023-01-01'");
  });

  test('SQL injection: prevent SQL injection payloads', async () => {
    const maliciousInput = "' OR '1'='1";
    prisma.$queryRawUnsafe.mockResolvedValue([]);
    const result = await getRecordsByTable('users', { status: maliciousInput });
    expect(result).toEqual([]);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM users WHERE 1=1 AND status = '${maliciousInput}'`);
  });

  test('path traversal: safely handle path traversal strings', async () => {
    const maliciousPath = "../../etc/passwd";
    prisma.$queryRawUnsafe.mockResolvedValue([]);
    const result = await getRecordsByTable(maliciousPath, { status: 'active' });
    expect(result).toEqual([]);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM ../../etc/passwd WHERE 1=1 AND status = 'active'`);
  });

  test('oversized input: handle oversized inputs gracefully', async () => {
    const oversizedInput = 'x'.repeat(10000);
    prisma.$queryRawUnsafe.mockResolvedValue([]);
    const result = await getRecordsByTable(oversizedInput, { status: 'active' });
    expect(result).toEqual([]);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM ${oversizedInput} WHERE 1=1 AND status = 'active'`);
  });

  test('boundary values: handle integer boundaries correctly', async () => {
    const mockRecords = [{ id: 0, status: 'active', created_at: '2023-01-01' }];
    prisma.$queryRawUnsafe.mockResolvedValue(mockRecords);
    const resultZero = await getRecordsByTable('my_table', { status: 0 });
    expect(resultZero).toEqual(mockRecords);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM my_table WHERE 1=1 AND status = '0'`);

    const resultNegative = await getRecordsByTable('my_table', { status: -1 });
    expect(resultNegative).toEqual(mockRecords);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM my_table WHERE 1=1 AND status = '-1'`);

    const resultMaxInt = await getRecordsByTable('my_table', { status: Number.MAX_SAFE_INTEGER });
    expect(resultMaxInt).toEqual(mockRecords);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM my_table WHERE 1=1 AND status = '${Number.MAX_SAFE_INTEGER}'`);
  });
});

// --- getStatsByCategory (line 36) ---
const prisma = require('@prisma/client');
const { getStatsByCategory } = require('./prisma-unsafe');

jest.mock('@prisma/client');

describe('getStatsByCategory', () => {
  beforeEach(() => {
    prisma.$queryRawUnsafe.mockReset();
  });

  test('should return stats for valid category and metric', async () => {
    const mockResult = [{ metricValue: 'example', count: 10 }];
    prisma.$queryRawUnsafe.mockResolvedValue(mockResult);

    const result = await getStatsByCategory('electronics', 'metricValue');
    expect(result).toEqual(mockResult);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledTimes(1);
  });

  test('should handle SQL injection payloads', async () => {
    const maliciousInput = "electronics'; DROP TABLE products; --";
    const mockResult = [{ metricValue: 'example', count: 10 }];
    prisma.$queryRawUnsafe.mockResolvedValue(mockResult);

    const result = await getStatsByCategory(maliciousInput, 'metricValue');
    expect(result).toEqual(mockResult);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalled();
  });

  test('should handle path traversal strings', async () => {
    const pathTraversalInput = '../../etc/passwd';
    const mockResult = [{ metricValue: 'example', count: 10 }];
    prisma.$queryRawUnsafe.mockResolvedValue(mockResult);

    const result = await getStatsByCategory(pathTraversalInput, 'metricValue');
    expect(result).toEqual(mockResult);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalled();
  });

  test('should handle oversized inputs', async () => {
    const oversizedInput = 'x'.repeat(10000);
    const mockResult = [{ metricValue: 'example', count: 10 }];
    prisma.$queryRawUnsafe.mockResolvedValue(mockResult);

    const result = await getStatsByCategory(oversizedInput, 'metricValue');
    expect(result).toEqual(mockResult);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalled();
  });

  test('should handle boundary values for integers', async () => {
    const mockResult = [{ metricValue: 'example', count: 10 }];
    prisma.$queryRawUnsafe.mockResolvedValue(mockResult);

    const result = await getStatsByCategory('electronics', 0);
    expect(result).toEqual(mockResult);

    const negativeResult = await getStatsByCategory('electronics', -1);
    expect(negativeResult).toEqual(mockResult);

    const maxIntResult = await getStatsByCategory('electronics', Number.MAX_SAFE_INTEGER);
    expect(maxIntResult).toEqual(mockResult);
  });

  test('should handle null inputs', async () => {
    const mockResult = [{ metricValue: 'example', count: 10 }];
    prisma.$queryRawUnsafe.mockResolvedValue(mockResult);

    const result = await getStatsByCategory(null, null);
    expect(result).toEqual(mockResult);
  });
});

// --- getTopUsers (line 46) ---
const prisma = require('@prisma/client');
const { getTopUsers } = require('./prisma-unsafe');

jest.mock('@prisma/client', () => ({
  $queryRawUnsafe: jest.fn(),
}));

describe('getTopUsers', () => {
  const mockedUsers = [{ id: 1 }, { id: 2 }];
  afterEach(() => {
    jest.clearAllMocks();
  });

  test('happy path - valid inputs', async () => {
    const limit = 2;
    const condition = 'amount > 100';
    prisma.$queryRawUnsafe.mockResolvedValue(mockedUsers);
    const result = await getTopUsers(limit, condition);
    expect(result).toEqual(mockedUsers);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(expect.stringContaining('LIMIT 2'));
  });

  test('SQL injection - single quote', async () => {
    const limit = 2;
    const condition = "' OR '1'='1";
    prisma.$queryRawUnsafe.mockResolvedValue(mockedUsers);
    await getTopUsers(limit, condition);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(expect.stringContaining("' OR '1'='1"));
  });

  test('Path Traversal - attempt', async () => {
    const limit = 2;
    const condition = '../etc/passwd';
    prisma.$queryRawUnsafe.mockResolvedValue(mockedUsers);
    await getTopUsers(limit, condition);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(expect.stringContaining('../etc/passwd'));
  });

  test('Oversized input', async () => {
    const limit = 1000000;
    const condition = '1=1';
    prisma.$queryRawUnsafe.mockResolvedValue(mockedUsers);
    const result = await getTopUsers(limit, condition);
    expect(result).toEqual(mockedUsers);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(expect.stringContaining('LIMIT 1000000'));
  });

  test('Boundary value - zero limit', async () => {
    const limit = 0;
    const condition = 'amount > 100';
    prisma.$queryRawUnsafe.mockResolvedValue([]);
    const result = await getTopUsers(limit, condition);
    expect(result).toEqual([]);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(expect.stringContaining('LIMIT 0'));
  });

  test('Boundary value - negative limit', async () => {
    const limit = -1;
    const condition = 'amount > 100';
    prisma.$queryRawUnsafe.mockResolvedValue([]);
    const result = await getTopUsers(limit, condition);
    expect(result).toEqual([]);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(expect.stringContaining('LIMIT -1'));
  });

  test('Boundary value - maximum integer limit', async () => {
    const limit = Number.MAX_SAFE_INTEGER;
    const condition = 'amount > 100';
    prisma.$queryRawUnsafe.mockResolvedValue(mockedUsers);
    const result = await getTopUsers(limit, condition);
    expect(result).toEqual(mockedUsers);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(expect.stringContaining(`LIMIT ${Number.MAX_SAFE_INTEGER}`));
  });
});

