// Auto-generated by deepguard testgen — 2026-07-10T20:10:10+03:30
// Source: sequelize-dynamic.js

// --- getCustomColumns (line 11) ---
const sequelize = require('sequelize');

jest.mock('sequelize', () => ({
  query: jest.fn(),
}));

const { getCustomColumns } = require('./sequelize-dynamic');

describe('getCustomColumns', () => {
  afterEach(() => {
    jest.clearAllMocks();
  });

  test('should return results with valid inputs', async () => {
    const mockResults = [{ id: 1, name: 'John Doe' }];
    sequelize.query.mockResolvedValue([mockResults]);
    const results = await getCustomColumns('users', ['id', 'name']);
    expect(results).toEqual(mockResults);
    expect(sequelize.query).toHaveBeenCalledWith('SELECT id, name FROM users');
  });

  test('should handle SQL injection input', async () => {
    const sqlInjection = "id, (SELECT * FROM users WHERE '1'='1') as unsafe";
    sequelize.query.mockResolvedValue([[]]);
    const results = await getCustomColumns('users', [sqlInjection]);
    expect(results).toEqual([]);
    expect(sequelize.query).toHaveBeenCalledWith(`SELECT ${sqlInjection} FROM users`);
  });

  test('should handle path traversal strings', async () => {
    const pathTraversal = "..\/..\/etc\/passwd";
    sequelize.query.mockResolvedValue([[]]);
    const results = await getCustomColumns('users', [pathTraversal]);
    expect(results).toEqual([]);
    expect(sequelize.query).toHaveBeenCalledWith(`SELECT ${pathTraversal} FROM users`);
  });

  test('should handle oversized inputs', async () => {
    const oversizedColumns = new Array(1001).fill('column').map((_, i) => `column${i}`).join(', ');
    sequelize.query.mockResolvedValue([[]]);
    const results = await getCustomColumns('users', [oversizedColumns]);
    expect(results).toEqual([]);
  });

  test('should handle null input', async () => {
    sequelize.query.mockResolvedValue([[]]);
    const results = await getCustomColumns('users', null);
    expect(results).toEqual([]);
  });

  test('should handle integer boundary values', async () => {
    sequelize.query.mockResolvedValue([[]]);
    const resultsZero = await getCustomColumns('users', [0]);
    const resultsNegative = await getCustomColumns('users', [-1]);
    const resultsMaxInt = await getCustomColumns('users', [Number.MAX_SAFE_INTEGER]);
    expect(resultsZero).toEqual([]);
    expect(resultsNegative).toEqual([]);
    expect(resultsMaxInt).toEqual([]);
  });
});

// --- getJoinedData (line 18) ---
import { sequelize } from './your-sequelize-setup-file';

jest.mock('./your-sequelize-setup-file', () => ({
  sequelize: {
    query: jest.fn(),
  },
}));

import { getJoinedData } from './sequelize-dynamic';

describe('getJoinedData', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  test('should return joined data for valid inputs', async () => {
    const mockResults = [{ id: 1, name: 'Test' }];
    sequelize.query.mockResolvedValue([mockResults]);

    const result = await getJoinedData('users', 'posts', 'users.id = posts.user_id');
    expect(result).toEqual(mockResults);
    expect(sequelize.query).toHaveBeenCalledWith(`
      SELECT *
      FROM users t1
      INNER JOIN posts t2 ON users.id = posts.user_id
    `);
  });

  test('should handle SQL injection payloads', async () => {
    const sqlInjection = "users; DROP TABLE users; --";
    sequelize.query.mockResolvedValue([[]]);

    const result = await getJoinedData(sqlInjection, 'posts', '1=1');
    expect(result).toEqual([]);
    expect(sequelize.query).toHaveBeenCalledWith(`
      SELECT *
      FROM users; DROP TABLE users; -- t1
      INNER JOIN posts t2 ON 1=1
    `);
  });

  test('should handle path traversal strings', async () => {
    const pathTraversal = "../../etc/passwd";
    sequelize.query.mockResolvedValue([[]]);

    const result = await getJoinedData(pathTraversal, 'posts', '1=1');
    expect(result).toEqual([]);
    expect(sequelize.query).toHaveBeenCalledWith(`
      SELECT *
      FROM ../../etc/passwd t1
      INNER JOIN posts t2 ON 1=1
    `);
  });

  test('should handle oversized input', async () => {
    const oversizedInput = 'a'.repeat(10000);
    sequelize.query.mockResolvedValue([[]]);

    const result = await getJoinedData(oversizedInput, oversizedInput, oversizedInput);
    expect(result).toEqual([]);
    expect(sequelize.query).toHaveBeenCalled();
  });

  test('should handle null input', async () => {
    const result = await getJoinedData(null, null, null);
    expect(result).toBeUndefined();
    expect(sequelize.query).not.toHaveBeenCalled();
  });

  test('should handle integer boundary values', async () => {
    sequelize.query.mockResolvedValue([[{ id: 0, name: 'Zero' }]]);
    const resultZero = await getJoinedData('users', 'posts', 'users.id = posts.user_id');
    expect(resultZero).toEqual([{ id: 0, name: 'Zero' }]);

    sequelize.query.mockResolvedValue([[{ id: -1, name: 'Negative' }]]);
    const resultNegative = await getJoinedData('users', 'posts', 'users.id = posts.user_id');
    expect(resultNegative).toEqual([{ id: -1, name: 'Negative' }]);

    sequelize.query.mockResolvedValue([[{ id: Number.MAX_SAFE_INTEGER, name: 'MaxInt' }]]);
    const resultMaxInt = await getJoinedData('users', 'posts', 'users.id = posts.user_id');
    expect(resultMaxInt).toEqual([{ id: Number.MAX_SAFE_INTEGER, name: 'MaxInt' }]);
  });
});

// --- getAggregatedData (line 28) ---
const { getAggregatedData } = require('../path/to/your/module');
const sequelize = require('sequelize');

jest.mock('sequelize', () => ({
  query: jest.fn()
}));

describe('getAggregatedData', () => {
  beforeEach(() => {
    sequelize.query.mockClear();
  });

  test('should return aggregated data for valid inputs', async () => {
    const mockData = [{ result: 100 }];
    sequelize.query.mockResolvedValue([mockData]);
    const result = await getAggregatedData('groupField', 'SUM', 'tableName');
    expect(result).toEqual(mockData);
    expect(sequelize.query).toHaveBeenCalledTimes(1);
  });
  
  test('should handle SQL injection payloads', async () => {
    const injectionPayload = "groupField; DROP TABLE users; --";
    const mockData = [{ result: 0 }];
    sequelize.query.mockResolvedValue([mockData]);
    const result = await getAggregatedData(injectionPayload, 'SUM', 'tableName');
    expect(result).toEqual(mockData);
    expect(sequelize.query).toHaveBeenCalledWith(expect.stringContaining('SELECT groupField; DROP TABLE users; --'));
  });
  
  test('should handle path traversal strings', async () => {
    const pathTraversal = '../../etc/passwd';
    const mockData = [{ result: 0 }];
    sequelize.query.mockResolvedValue([mockData]);
    const result = await getAggregatedData(pathTraversal, 'SUM', 'tableName');
    expect(result).toEqual(mockData);
    expect(sequelize.query).toHaveBeenCalledWith(expect.stringContaining('../../etc/passwd'));
  });
  
  test('should handle oversized inputs', async () => {
    const oversizedInput = 'A'.repeat(10000);
    const mockData = [{ result: 0 }];
    sequelize.query.mockResolvedValue([mockData]);
    const result = await getAggregatedData(oversizedInput, 'SUM', 'tableName');
    expect(result).toEqual(mockData);
    expect(sequelize.query).toHaveBeenCalledTimes(1);
  });
  
  test('should handle integer boundary values', async () => {
    const maxInt = Number.MAX_SAFE_INTEGER;
    const minInt = -1;
    const zero = 0;
    const mockData = [{ result: 0 }];
    sequelize.query.mockResolvedValue([mockData]);
    await getAggregatedData(maxInt.toString(), 'SUM', 'tableName');
    await getAggregatedData(minInt.toString(), 'SUM', 'tableName');
    await getAggregatedData(zero.toString(), 'SUM', 'tableName');
    expect(sequelize.query).toHaveBeenCalledTimes(3);
  });
});

// --- getFilteredAggregates (line 38) ---
const { getFilteredAggregates } = require('./sequelize-dynamic');
const sequelize = require('sequelize');

jest.mock('sequelize');

describe('getFilteredAggregates', () => {
  beforeEach(() => {
    sequelize.query = jest.fn();
  });

  test('happy path: valid inputs and expected output', async () => {
    const category = 'electronics';
    const havingCondition = 'count > 10';
    const expectedResponse = [{ category: 'electronics', count: 15 }];
    sequelize.query.mockResolvedValueOnce([expectedResponse]);

    const result = await getFilteredAggregates(category, havingCondition);
    expect(result).toEqual(expectedResponse);
    expect(sequelize.query).toHaveBeenCalledWith(expect.stringContaining(category));
  });

  test('SQL injection payload prevents execution', async () => {
    const category = 'electronics; DROP TABLE products; --';
    const havingCondition = 'count > 10';
    const expectedResponse = []; 
    sequelize.query.mockResolvedValueOnce([expectedResponse]);

    const result = await getFilteredAggregates(category, havingCondition);
    expect(result).toEqual(expectedResponse);
    expect(sequelize.query).toHaveBeenCalledWith(expect.not.stringContaining('DROP TABLE')); 
  });

  test('path traversal attack', async () => {
    const category = '../../etc/passwd';
    const havingCondition = 'count > 10';
    const expectedResponse = []; 
    sequelize.query.mockResolvedValueOnce([expectedResponse]);

    const result = await getFilteredAggregates(category, havingCondition);
    expect(result).toEqual(expectedResponse);
    expect(sequelize.query).toHaveBeenCalledWith(expect.not.stringContaining('etc/passwd')); 
  });

  test('oversized inputs', async () => {
    const category = 'a'.repeat(10000); // oversized string
    const havingCondition = 'count > 10';
    const expectedResponse = []; 
    sequelize.query.mockResolvedValueOnce([expectedResponse]);

    const result = await getFilteredAggregates(category, havingCondition);
    expect(result).toEqual(expectedResponse);
    expect(sequelize.query).toHaveBeenCalled();
  });

  test('null input', async () => {
    const category = null;
    const havingCondition = 'count > 10';
    const expectedResponse = []; 
    sequelize.query.mockResolvedValueOnce([expectedResponse]);

    const result = await getFilteredAggregates(category, havingCondition);
    expect(result).toEqual(expectedResponse);
    expect(sequelize.query).toHaveBeenCalled();
  });

  test('integer boundary values', async () => {
    const category = 'electronics';
    const havingCondition = 'count = 0';
    const expectedResponseZero = [{ category: 'electronics', count: 0 }];
    sequelize.query.mockResolvedValueOnce([expectedResponseZero]);

    const resultZero = await getFilteredAggregates(category, havingCondition);
    expect(resultZero).toEqual(expectedResponseZero);

    const havingConditionNegative = 'count = -1';
    const expectedResponseNegative = []; 
    sequelize.query.mockResolvedValueOnce([expectedResponseNegative]);

    const resultNegative = await getFilteredAggregates(category, havingConditionNegative);
    expect(resultNegative).toEqual(expectedResponseNegative);

    const havingConditionMaxInt = 'count = 2147483647';
    const expectedResponseMaxInt = [{ category: 'electronics', count: 2147483647 }];
    sequelize.query.mockResolvedValueOnce([expectedResponseMaxInt]);

    const resultMaxInt = await getFilteredAggregates(category, havingConditionMaxInt);
    expect(resultMaxInt).toEqual(expectedResponseMaxInt);
  });
});

// --- searchAcrossTables (line 50) ---
const sequelize = require('sequelize');
const { searchAcrossTables } = require('./path/to/your/module');

jest.mock('sequelize', () => ({
  query: jest.fn()
}));

describe('searchAcrossTables', () => {
  afterEach(() => {
    jest.clearAllMocks();
  });

  test('should return results for valid inputs', async () => {
    const mockResults = [{ name: 'test1' }, { name: 'test2' }];
    sequelize.query.mockResolvedValue([mockResults]);

    const results = await searchAcrossTables('test', ['table1', 'table2']);
    expect(results).toEqual(mockResults);
    expect(sequelize.query).toHaveBeenCalledWith(
      expect.stringContaining("SELECT * FROM table1 WHERE name LIKE '%test%'"),
    );
  });

  test('should handle SQL injection payloads', async () => {
    const sqlInjection = '1; DROP TABLE users;';
    const mockResults = [];
    sequelize.query.mockResolvedValue([mockResults]);

    const results = await searchAcrossTables(sqlInjection, ['table1']);
    expect(results).toEqual(mockResults);
    expect(sequelize.query).toHaveBeenCalledWith(
      expect.stringContaining(`SELECT * FROM table1 WHERE name LIKE '%${sqlInjection}%'`),
    );
  });

  test('should handle path traversal strings', async () => {
    const pathTraversal = '../../etc/passwd';
    const mockResults = [];
    sequelize.query.mockResolvedValue([mockResults]);

    const results = await searchAcrossTables(pathTraversal, ['table1']);
    expect(results).toEqual(mockResults);
    expect(sequelize.query).toHaveBeenCalledWith(
      expect.stringContaining(`SELECT * FROM table1 WHERE name LIKE '%${pathTraversal}%'`),
    );
  });

  test('should handle oversized input', async () => {
    const oversizedString = 'a'.repeat(10000);
    const mockResults = [];
    sequelize.query.mockResolvedValue([mockResults]);

    const results = await searchAcrossTables(oversizedString, ['table1']);
    expect(results).toEqual(mockResults);
    expect(sequelize.query).toHaveBeenCalledWith(
      expect.stringContaining(`SELECT * FROM table1 WHERE name LIKE '%${oversizedString}%'`),
    );
  });

  test('should handle null input', async () => {
    const mockResults = [];
    sequelize.query.mockResolvedValue([mockResults]);

    const results = await searchAcrossTables(null, ['table1']);
    expect(results).toEqual(mockResults);
    expect(sequelize.query).toHaveBeenCalledWith(
      expect.stringContaining(`SELECT * FROM table1 WHERE name LIKE '%%'`),
    );
  });

  test('should handle integer boundary values', async () => {
    const negativeValue = -1;
    const mockResults = [];
    sequelize.query.mockResolvedValue([mockResults]);

    const results = await searchAcrossTables(negativeValue, ['table1']);
    expect(results).toEqual(mockResults);
    expect(sequelize.query).toHaveBeenCalledWith(
      expect.stringContaining(`SELECT * FROM table1 WHERE name LIKE '%${negativeValue}%'`),
    );

    const zeroValue = 0;
    await searchAcrossTables(zeroValue, ['table1']);
    expect(sequelize.query).toHaveBeenCalledWith(
      expect.stringContaining(`SELECT * FROM table1 WHERE name LIKE '%${zeroValue}%'`),
    );

    const maxInt = Number.MAX_SAFE_INTEGER;
    await searchAcrossTables(maxInt, ['table1']);
    expect(sequelize.query).toHaveBeenCalledWith(
      expect.stringContaining(`SELECT * FROM table1 WHERE name LIKE '%${maxInt}%'`),
    );
  });
});

// --- deleteRecords (line 59) ---
const sequelize = require('sequelize');

jest.mock('sequelize', () => ({
  query: jest.fn(),
}));

const { deleteRecords } = require('./sequelize-dynamic');

describe('deleteRecords', () => {
  afterEach(() => {
    jest.clearAllMocks();
  });

  // Happy path
  test('should delete records from valid table with valid condition', async () => {
    const tableName = 'users';
    const condition = 'id = 1';
    sequelize.query.mockResolvedValueOnce([1]);
    const result = await deleteRecords(tableName, condition);
    expect(result).toBe(true);
    expect(sequelize.query).toHaveBeenCalledWith(`DELETE FROM ${tableName} WHERE ${condition}`);
  });

  // SQL Injection
  test('should handle SQL injection payload', async () => {
    const tableName = 'users';
    const condition = "1; DROP TABLE users; --";
    sequelize.query.mockResolvedValueOnce([1]);
    const result = await deleteRecords(tableName, condition);
    expect(result).toBe(true);
    expect(sequelize.query).toHaveBeenCalledWith(`DELETE FROM ${tableName} WHERE ${condition}`);
  });

  // Path traversal strings (if applicable)
  test('should handle path traversal strings', async () => {
    const tableName = '../../etc/passwd';
    const condition = 'id = 1';
    sequelize.query.mockResolvedValueOnce([1]);
    const result = await deleteRecords(tableName, condition);
    expect(result).toBe(true);
    expect(sequelize.query).toHaveBeenCalledWith(`DELETE FROM ${tableName} WHERE ${condition}`);
  });

  // Oversized input
  test('should handle oversized input', async () => {
    const tableName = 'users';
    const condition = 'id = ' + '1'.repeat(10000);
    sequelize.query.mockResolvedValueOnce([1]);
    const result = await deleteRecords(tableName, condition);
    expect(result).toBe(true);
    expect(sequelize.query).toHaveBeenCalledWith(`DELETE FROM ${tableName} WHERE ${condition}`);
  });

  // Integer boundary values
  test('should handle integer boundary values', async () => {
    const tableName = 'users';
    const conditionZero = 'id = 0';
    const conditionNegative = 'id = -1';
    const conditionMaxInt = 'id = 2147483647';
    sequelize.query.mockResolvedValueOnce([1]);

    await deleteRecords(tableName, conditionZero);
    expect(sequelize.query).toHaveBeenCalledWith(`DELETE FROM ${tableName} WHERE ${conditionZero}`);

    await deleteRecords(tableName, conditionNegative);
    expect(sequelize.query).toHaveBeenCalledWith(`DELETE FROM ${tableName} WHERE ${conditionNegative}`);

    await deleteRecords(tableName, conditionMaxInt);
    expect(sequelize.query).toHaveBeenCalledWith(`DELETE FROM ${tableName} WHERE ${conditionMaxInt}`);
  });
});

