// Auto-generated by deepguard testgen — 2026-07-10T20:13:44+03:30
// Source: typescript-express.ts

// --- anonymous (line 31) ---
import { Request, Response } from 'express';
import { pool } from '../db';
import { yourFunction } from './typescript-express';

jest.mock('../db');

describe('yourFunction', () => {
  let req: Partial<Request>;
  let res: Partial<Response>;

  beforeEach(() => {
    req = { params: { id: '' } };
    res = { json: jest.fn(), status: jest.fn().mockReturnThis() };
  });

  test('should return user data for valid ID', async () => {
    req.params.id = '1';
    (pool.query as jest.Mock).mockResolvedValue([{ id: 1, name: 'John Doe' }]);

    await yourFunction(req as Request, res as Response);

    expect(res.json).toHaveBeenCalledWith([{ id: 1, name: 'John Doe' }]);
    expect(res.status).not.toHaveBeenCalled();
  });

  test('should handle SQL injection', async () => {
    req.params.id = '1 OR 1=1';
    (pool.query as jest.Mock).mockResolvedValue([]);

    await yourFunction(req as Request, res as Response);

    expect(pool.query).toHaveBeenCalledWith("SELECT * FROM users WHERE id = 1 OR 1=1");
    expect(res.json).toHaveBeenCalledWith([]);
  });

  test('should handle path traversal attack', async () => {
    req.params.id = '../etc/passwd';
    (pool.query as jest.Mock).mockResolvedValue([]);

    await yourFunction(req as Request, res as Response);

    expect(pool.query).toHaveBeenCalledWith("SELECT * FROM users WHERE id = ../etc/passwd");
    expect(res.json).toHaveBeenCalledWith([]);
  });

  test('should handle oversized input', async () => {
    req.params.id = 'a'.repeat(1000); // oversized input string
    (pool.query as jest.Mock).mockResolvedValue([]);

    await yourFunction(req as Request, res as Response);

    expect(pool.query).toHaveBeenCalledWith("SELECT * FROM users WHERE id = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...");
    expect(res.json).toHaveBeenCalledWith([]);
  });

  test('should handle negative integer and zero boundary values', async () => {
    const ids = [0, -1, Number.MAX_SAFE_INTEGER];
    for (const id of ids) {
      req.params.id = id.toString();
      (pool.query as jest.Mock).mockResolvedValue([{ id, name: 'User' }]);

      await yourFunction(req as Request, res as Response);

      expect(res.json).toHaveBeenCalledWith([{ id, name: 'User' }]);
    }
  });

  test('should return error for database query failure', async () => {
    req.params.id = '1';
    (pool.query as jest.Mock).mockRejectedValue(new Error('Database error'));

    await yourFunction(req as Request, res as Response);

    expect(res.status).toHaveBeenCalledWith(500);
    expect(res.json).toHaveBeenCalledWith({ error: 'Database error' });
  });
});

// --- anonymous (line 48) ---
import { Request, Response } from 'express';
import { pool } from './database';
import { LoginRequest } from './types';

const mockRequest = (body: Partial<LoginRequest>) => ({ body }) as Request;
const mockResponse = () => {
  const res: Partial<Response> = {};
  res.json = jest.fn().mockReturnValue(res);
  res.status = jest.fn().mockReturnValue(res);
  return res as Response;
};

describe('Login Endpoint', () => {
  it('should return success with valid credentials', async () => {
    const req = mockRequest({ username: 'validUser', password: 'validPass' });
    const res = mockResponse();

    jest.spyOn(pool, 'query').mockResolvedValue([[{ id: 1, username: 'validUser' }]]);

    await loginHandler(req, res);

    expect(res.json).toHaveBeenCalledWith({ success: true, user: { id: 1, username: 'validUser' } });
  });

  it('should return 401 for invalid credentials', async () => {
    const req = mockRequest({ username: 'invalidUser', password: 'invalidPass' });
    const res = mockResponse();

    jest.spyOn(pool, 'query').mockResolvedValue([[ ]]);

    await loginHandler(req, res);

    expect(res.status).toHaveBeenCalledWith(401);
    expect(res.json).toHaveBeenCalledWith({ success: false });
  });

  it('should handle SQL injection attempts', async () => {
    const req = mockRequest({ username: "' OR '1'='1", password: "' OR '1'='1" });
    const res = mockResponse();

    jest.spyOn(pool, 'query').mockResolvedValue([[ ]]);

    await loginHandler(req, res);

    expect(res.status).toHaveBeenCalledWith(401);
    expect(res.json).toHaveBeenCalledWith({ success: false });
  });

  it('should handle oversized inputs', async () => {
    const longString = 'A'.repeat(1001);
    const req = mockRequest({ username: longString, password: longString });
    const res = mockResponse();

    jest.spyOn(pool, 'query').mockResolvedValue([[ ]]);

    await loginHandler(req, res);

    expect(res.status).toHaveBeenCalledWith(401);
    expect(res.json).toHaveBeenCalledWith({ success: false });
  });

  it('should handle null inputs', async () => {
    const req = mockRequest({ username: null, password: null });
    const res = mockResponse();

    await loginHandler(req, res);

    expect(res.status).toHaveBeenCalledWith(401);
    expect(res.json).toHaveBeenCalledWith({ success: false });
  });

  it('should handle boundary integer values', async () => {
    const req = mockRequest({ username: 'user', password: String(Number.MAX_SAFE_INTEGER) });
    const res = mockResponse();

    jest.spyOn(pool, 'query').mockResolvedValue([[ { id: 1, username: 'user' } ]]);

    await loginHandler(req, res);

    expect(res.json).toHaveBeenCalledWith({ success: true, user: { id: 1, username: 'user' } });
  });
});

// --- searchProducts (line 64) ---
import { Request, Response } from 'express';
import { searchProducts } from './typescript-express';
import { pool } from './database';
import { jest } from '@jest/globals';

jest.mock('./database');

describe('searchProducts', () => {
  const mockResponse = () => {
    const res: Partial<Response> = {};
    res.json = jest.fn();
    res.status = jest.fn().mockReturnValue(res);
    return res;
  };

  it('should return products matching valid search term and category', async () => {
    const req = {
      query: { q: 'valid', category: 'electronics' }
    } as Request;
    const res = mockResponse();

    (pool.query as jest.Mock).mockResolvedValue([[{ id: 1, name: 'valid product', category: 'electronics' }]]);

    await searchProducts(req, res as Response);

    expect(res.json).toHaveBeenCalledWith([{ id: 1, name: 'valid product', category: 'electronics' }]);
  });

  it('should handle SQL injection attempts', async () => {
    const req = {
      query: { q: '; DROP TABLE products;', category: 'electronics' }
    } as Request;
    const res = mockResponse();

    (pool.query as jest.Mock).mockResolvedValue([[{ id: 1, name: 'mock product', category: 'electronics' }]]);

    await searchProducts(req, res as Response);

    expect(pool.query).toHaveBeenCalledWith(expect.not.stringContaining('; DROP TABLE')); // Check for SQL injection
  });

  it('should handle path traversal attempts in category', async () => {
    const req = {
      query: { q: 'product', category: '../../etc/passwd' }
    } as Request;
    const res = mockResponse();

    (pool.query as jest.Mock).mockResolvedValue([[{ id: 1, name: 'mock product', category: 'invalid' }]]);

    await searchProducts(req, res as Response);

    expect(pool.query).toHaveBeenCalledWith(expect.not.stringContaining('../../etc/passwd')); // Check for path traversal
  });

  it('should handle oversized query input', async () => {
    const req = {
      query: { q: 'a'.repeat(10000), category: 'electronics' }
    } as Request;
    const res = mockResponse();

    await searchProducts(req, res as Response);

    expect(res.json).toHaveBeenCalled();
  });

  it('should handle null inputs gracefully', async () => {
    const req = {
      query: { q: null, category: null }
    } as Request;
    const res = mockResponse();

    await searchProducts(req, res as Response);

    expect(res.json).toHaveBeenCalled();
  });

  it('should handle integer boundary values', async () => {
    const req = {
      query: { q: 0, category: -1 } // This might depend on your use-case
    } as unknown as Request;
    const res = mockResponse();

    (pool.query as jest.Mock).mockResolvedValue([[{ id: 0, name: 'boundary product', category: 'e' }]]);

    await searchProducts(req, res as Response);

    expect(res.json).toHaveBeenCalledWith([{ id: 0, name: 'boundary product', category: 'e' }]);
  });
});

// --- updateUser (line 85) ---
import { Request, Response } from 'express';
import { pool } from './db';
import { updateUser } from './typescript-express';

jest.mock('./db');

describe('updateUser', () => {
  const mockRequest = (params: Partial<Record<'id', string>>, body: Partial<Record<'email', string>>): Request => ({
    params: { ...params },
    body: { ...body }
  } as Request);

  const mockResponse = (): Response => {
    const res = {} as Response;
    res.json = jest.fn().mockReturnValue(res);
    res.status = jest.fn().mockReturnValue(res);
    return res;
  };

  it('should update user email successfully', async () => {
    const req = mockRequest({ id: '1' }, { email: 'test@example.com' });
    const res = mockResponse();

    (pool.query as jest.Mock).mockResolvedValueOnce(undefined);

    await updateUser(req, res);

    expect(res.json).toHaveBeenCalledWith({ success: true });
    expect(pool.query).toHaveBeenCalledWith("UPDATE users SET email = 'test@example.com' WHERE id = 1");
  });

  it('should handle SQL injection payload', async () => {
    const req = mockRequest({ id: '1' }, { email: "test@example.com', 'DROP TABLE users; --" });
    const res = mockResponse();

    (pool.query as jest.Mock).mockResolvedValueOnce(undefined);

    await updateUser(req, res);

    expect(res.json).toHaveBeenCalledWith({ success: true });
    expect(pool.query).toHaveBeenCalledWith("UPDATE users SET email = 'test@example.com', 'DROP TABLE users; --' WHERE id = 1");
  });

  it('should handle path traversal strings', async () => {
    const req = mockRequest({ id: '1' }, { email: '../etc/passwd' });
    const res = mockResponse();

    (pool.query as jest.Mock).mockResolvedValueOnce(undefined);

    await updateUser(req, res);

    expect(res.json).toHaveBeenCalledWith({ success: true });
    expect(pool.query).toHaveBeenCalledWith("UPDATE users SET email = '../etc/passwd' WHERE id = 1");
  });

  it('should handle oversized email input', async () => {
    const longEmail = 'a'.repeat(300); // assuming 300 is larger than expected
    const req = mockRequest({ id: '1' }, { email: longEmail });
    const res = mockResponse();

    (pool.query as jest.Mock).mockResolvedValueOnce(undefined);

    await updateUser(req, res);

    expect(res.json).toHaveBeenCalledWith({ success: true });
    expect(pool.query).toHaveBeenCalledWith(`UPDATE users SET email = '${longEmail}' WHERE id = 1`);
  });

  it('should handle null email input', async () => {
    const req = mockRequest({ id: '1' }, { email: null });
    const res = mockResponse();

    (pool.query as jest.Mock).mockResolvedValueOnce(undefined);

    await updateUser(req, res);

    expect(res.json).toHaveBeenCalledWith({ success: true });
    expect(pool.query).toHaveBeenCalledWith("UPDATE users SET email = 'null' WHERE id = 1");
  });

  it('should handle integer boundary values', async () => {
    const req = mockRequest({ id: '2147483647' }, { email: 'boundary@example.com' }); // MAX_INT
    const res = mockResponse();

    (pool.query as jest.Mock).mockResolvedValueOnce(undefined);

    await updateUser(req, res);

    expect(res.json).toHaveBeenCalledWith({ success: true });
    expect(pool.query).toHaveBeenCalledWith("UPDATE users SET email = 'boundary@example.com' WHERE id = 2147483647");
  });

  it('should handle invalid integer input (negative)', async () => {
    const req = mockRequest({ id: '-1' }, { email: 'invalid@example.com' });
    const res = mockResponse();

    await updateUser(req, res);

    expect(res.status).toHaveBeenCalledWith(500);
  });
});

// --- anonymous (line 101) ---
import { Request, Response } from 'express';
import { userController } from './userController';

jest.mock('./userController');

describe('updateUser', () => {
  let req: Partial<Request>;
  let res: Partial<Response>;

  beforeEach(() => {
    req = {};
    res = { 
      status: jest.fn().mockReturnThis(),
      json: jest.fn(),
    };
  });

  test('should update user successfully with valid input', async () => {
    req = { body: { id: 1, name: 'John Doe' } };
    (userController.updateUser as jest.Mock).mockResolvedValueOnce({ success: true });
    await userController.updateUser(req as Request, res as Response);
    expect(res.status).toHaveBeenCalledWith(200);
    expect(res.json).toHaveBeenCalledWith({ success: true });
  });

  test('should handle SQL injection payloads', async () => {
    req = { body: { id: "1; DROP TABLE users; --", name: '恶意用户' } };
    (userController.updateUser as jest.Mock).mockResolvedValueOnce({ success: false });
    await userController.updateUser(req as Request, res as Response);
    expect(res.status).toHaveBeenCalledWith(400);
    expect(res.json).toHaveBeenCalledWith({ success: false });
  });

  test('should handle path traversal strings', async () => {
    req = { body: { id: 1, name: '../../etc/passwd' } };
    (userController.updateUser as jest.Mock).mockResolvedValueOnce({ success: false });
    await userController.updateUser(req as Request, res as Response);
    expect(res.status).toHaveBeenCalledWith(400);
    expect(res.json).toHaveBeenCalledWith({ success: false });
  });

  test('should handle oversized input', async () => {
    const oversizedName = 'a'.repeat(1001); // assuming max length is 1000
    req = { body: { id: 1, name: oversizedName } };
    (userController.updateUser as jest.Mock).mockResolvedValueOnce({ success: false });
    await userController.updateUser(req as Request, res as Response);
    expect(res.status).toHaveBeenCalledWith(400);
    expect(res.json).toHaveBeenCalledWith({ success: false });
  });

  test('should handle null input', async () => {
    req = { body: null };
    (userController.updateUser as jest.Mock).mockResolvedValueOnce({ success: false });
    await userController.updateUser(req as Request, res as Response);
    expect(res.status).toHaveBeenCalledWith(400);
    expect(res.json).toHaveBeenCalledWith({ success: false });
  });

  test('should handle integer boundary values', async () => {
    req = { body: { id: -1, name: 'John Doe' } };
    (userController.updateUser as jest.Mock).mockResolvedValueOnce({ success: false });
    await userController.updateUser(req as Request, res as Response);
    expect(res.status).toHaveBeenCalledWith(400);
    expect(res.json).toHaveBeenCalledWith({ success: false });
    
    req = { body: { id: 2147483647, name: 'John Doe' } };
    await userController.updateUser(req as Request, res as Response);
    expect(res.status).toHaveBeenCalledWith(400);
    expect(res.json).toHaveBeenCalledWith({ success: false });
  });
});

// --- anonymous (line 103) ---
import { Request, Response } from 'express';

describe('TypeScript Express Server', () => {
  const mockConsoleLog = jest.spyOn(console, 'log');

  afterEach(() => {
    jest.clearAllMocks();
  });

  test('should log server running on port 4000 (happy path)', () => {
    // Arrange
    const req = {} as Request;
    const res = {} as Response;

    // Act
    ((): void => {
      console.log('TypeScript Express server running on port 4000');
    })();

    // Assert
    expect(mockConsoleLog).toHaveBeenCalledWith('TypeScript Express server running on port 4000');
  });

  test('should handle SQL injection attempts gracefully', () => {
    // Arrange
    const req = { body: { query: "' OR '1'='1" } } as Request;
    const res = {} as Response;

    // Act
    ((): void => {
      const injectedQuery = req.body.query;
      console.log(`Received query: ${injectedQuery}`);
    })();

    // Assert
    expect(mockConsoleLog).toHaveBeenCalledWith("Received query: ' OR '1'='1");
  });

  test('should reject path traversal attempts', () => {
    // Arrange
    const req = { params: { path: '../etc/passwd' } } as Request;
    const res = {} as Response;

    // Act
    ((): void => {
      const requestedPath = req.params.path;
      console.log(`Requested path: ${requestedPath}`);
    })();

    // Assert
    expect(mockConsoleLog).toHaveBeenCalledWith("Requested path: ../etc/passwd");
  });

  test('should handle oversized input gracefully', () => {
    // Arrange
    const oversizedInput = 'x'.repeat(1000000);
    const req = { body: { input: oversizedInput } } as Request;
    const res = {} as Response;

    // Act
    ((): void => {
      console.log(`Input length: ${req.body.input.length}`);
    })();

    // Assert
    expect(mockConsoleLog).toHaveBeenCalledWith(`Input length: ${oversizedInput.length}`);
  });

  test('should handle integer boundary values', () => {
    // Arrange
    const boundaryValues = [0, -1, Number.MAX_SAFE_INTEGER];
    boundaryValues.forEach(value => {
      const req = { body: { number: value } } as Request;

      // Act
      ((): void => {
        console.log(`Received number: ${req.body.number}`);
      })();

      // Assert
      expect(mockConsoleLog).toHaveBeenCalledWith(`Received number: ${req.body.number}`);
    });
  });
});

