// Auto-generated by deepguard testgen — 2026-07-10T20:15:31+03:30
// Source: typescript-prisma.ts

// --- findUserById (line 22) ---
import { findUserById } from './typescript-prisma';
 import { PrismaClient } from '@prisma/client';

 jest.mock('@prisma/client');
 const mockedPrisma = PrismaClient as jest.Mocked<typeof PrismaClient>;

 describe('findUserById', () => {
   let prisma: PrismaClient;

   beforeEach(() => {
     prisma = new PrismaClient();
     mockedPrisma.mockImplementation(() => prisma);
   });

   afterEach(() => {
     jest.clearAllMocks();
   });

   it('should return the user for a valid userId', async () => {
     const userId = 1;
     const mockResponse = [{ id: 1, name: 'John Doe' }];
     prisma.$queryRaw.mockResolvedValueOnce(mockResponse);

     const result = await findUserById(userId);
     expect(result).toEqual(mockResponse);
     expect(prisma.$queryRaw).toHaveBeenCalledWith(expect.any(String));
     expect(prisma.$queryRaw).toHaveBeenCalledWith(`SELECT * FROM users WHERE id = ${userId}`);
   });

   it('should handle SQL injection attempts', async () => {
     const maliciousUserId = "1; DROP TABLE users;";
     prisma.$queryRaw.mockResolvedValueOnce([]);

     const result = await findUserById(maliciousUserId as any);
     expect(result).toEqual([]);
     expect(prisma.$queryRaw).toHaveBeenCalledWith(`SELECT * FROM users WHERE id = ${maliciousUserId}`);
   });

   it('should handle oversized input', async () => {
     const oversizedUserId = Number.MAX_SAFE_INTEGER + 1;
     prisma.$queryRaw.mockResolvedValueOnce([]);

     const result = await findUserById(oversizedUserId);
     expect(result).toEqual([]);
     expect(prisma.$queryRaw).toHaveBeenCalledWith(`SELECT * FROM users WHERE id = ${oversizedUserId}`);
   });

   it('should handle null input', async () => {
     const userId = null;
     await expect(findUserById(userId as any)).rejects.toThrow();
   });

   it('should handle boundary values properly', async () => {
     const testValues = [0, -1, Number.MAX_SAFE_INTEGER];
     for (const userId of testValues) {
       prisma.$queryRaw.mockResolvedValueOnce([{ id: userId, name: 'Boundary User' }]);

       const result = await findUserById(userId);
       expect(result).toEqual([{ id: userId, name: 'Boundary User' }]);
     }
   });
 });

// --- updateUserStatus (line 26) ---
import { updateUserStatus } from './typescript-prisma';
import { prisma } from './prismaClient';

jest.mock('./prismaClient');

describe('updateUserStatus', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('should update user status for valid inputs', async () => {
    const userId = 1;
    const status = 'active';
    (prisma.$executeRaw as jest.Mock).mockResolvedValue(1);

    const result = await updateUserStatus(userId, status);

    expect(prisma.$executeRaw).toHaveBeenCalledWith(expect.stringContaining(`UPDATE users SET status = ${status} WHERE id = ${userId}`));
    expect(result).toBe(1);
  });

  it('should handle SQL injection payloads', async () => {
    const userId = 1;
    const status = "'); DROP TABLE users; --";
    (prisma.$executeRaw as jest.Mock).mockResolvedValue(1);

    const result = await updateUserStatus(userId, status);

    expect(prisma.$executeRaw).toHaveBeenCalledWith(expect.stringContaining(`UPDATE users SET status = ${status} WHERE id = ${userId}`));
    expect(result).toBe(1);
  });

  it('should handle oversized input', async () => {
    const userId = 1;
    const status = 'a'.repeat(1001); // Assuming max length is 1000
    (prisma.$executeRaw as jest.Mock).mockResolvedValue(1);

    const result = await updateUserStatus(userId, status);

    expect(prisma.$executeRaw).toHaveBeenCalledWith(expect.stringContaining(`UPDATE users SET status = ${status} WHERE id = ${userId}`));
    expect(result).toBe(1);
  });

  it('should handle null status', async () => {
    const userId = 1;
    const status = null;
    (prisma.$executeRaw as jest.Mock).mockResolvedValue(1);

    const result = await updateUserStatus(userId, status);

    expect(prisma.$executeRaw).toHaveBeenCalledWith(expect.stringContaining(`UPDATE users SET status = ${status} WHERE id = ${userId}`));
    expect(result).toBe(1);
  });

  it('should handle userId as 0', async () => {
    const userId = 0;
    const status = 'active';
    (prisma.$executeRaw as jest.Mock).mockResolvedValue(1);

    const result = await updateUserStatus(userId, status);

    expect(prisma.$executeRaw).toHaveBeenCalledWith(expect.stringContaining(`UPDATE users SET status = ${status} WHERE id = ${userId}`));
    expect(result).toBe(1);
  });

  it('should handle userId as -1', async () => {
    const userId = -1;
    const status = 'inactive';
    (prisma.$executeRaw as jest.Mock).mockResolvedValue(1);

    const result = await updateUserStatus(userId, status);

    expect(prisma.$executeRaw).toHaveBeenCalledWith(expect.stringContaining(`UPDATE users SET status = ${status} WHERE id = ${userId}`));
    expect(result).toBe(1);
  });

  it('should handle maximum integer value for userId', async () => {
    const userId = Number.MAX_SAFE_INTEGER;
    const status = 'pending';
    (prisma.$executeRaw as jest.Mock).mockResolvedValue(1);

    const result = await updateUserStatus(userId, status);

    expect(prisma.$executeRaw).toHaveBeenCalledWith(expect.stringContaining(`UPDATE users SET status = ${status} WHERE id = ${userId}`));
    expect(result).toBe(1);
  });
});

// --- filterUsers (line 30) ---
import { filterUsers } from './typescript-prisma';
import { prisma } from './prismaClient';

jest.mock('./prismaClient');

describe('filterUsers', () => {
  const mockQueryRawUnsafe = prisma.$queryRawUnsafe as jest.Mock;

  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('should return users when valid filters are provided', async () => {
    const mockResponse = [{ id: 1, role: 'admin', status: 'active', age: 30 }];
    mockQueryRawUnsafe.mockResolvedValue(mockResponse);
    const filter = { role: 'admin', status: 'active', ageMin: 18, ageMax: 40 };

    const result = await filterUsers(filter);

    expect(mockQueryRawUnsafe).toHaveBeenCalledWith(
      "SELECT * FROM users WHERE 1=1 AND role = 'admin' AND status = 'active' AND age >= 18 AND age <= 40"
    );
    expect(result).toEqual(mockResponse);
  });

  it('should handle SQL injection payloads', async () => {
    const maliciousFilter = { role: 'admin; DROP TABLE users; --', status: 'active' };
    mockQueryRawUnsafe.mockResolvedValue([]);

    const result = await filterUsers(maliciousFilter);

    expect(mockQueryRawUnsafe).toHaveBeenCalledWith(
      "SELECT * FROM users WHERE 1=1 AND role = 'admin; DROP TABLE users; --' AND status = 'active'"
    );
    expect(result).toEqual([]);
  });

  it('should handle path traversal strings', async () => {
    const pathTraversalFilter = { role: '..//..//etc/passwd', status: 'active' };
    mockQueryRawUnsafe.mockResolvedValue([]);

    const result = await filterUsers(pathTraversalFilter);

    expect(mockQueryRawUnsafe).toHaveBeenCalledWith(
      "SELECT * FROM users WHERE 1=1 AND role = '..//..//etc/passwd' AND status = 'active'"
    );
    expect(result).toEqual([]);
  });

  it('should handle oversized inputs', async () => {
    const oversizedFilter = { role: 'a'.repeat(10000), status: 'active' };
    mockQueryRawUnsafe.mockResolvedValue([]);

    const result = await filterUsers(oversizedFilter);

    expect(mockQueryRawUnsafe).toHaveBeenCalledWith(
      expect.stringContaining('SELECT * FROM users WHERE 1=1 AND role = ')
    );
    expect(result).toEqual([]);
  });

  it('should handle null inputs properly', async () => {
    const nullFilter = { role: null, status: null, ageMin: null, ageMax: null };
    mockQueryRawUnsafe.mockResolvedValue([]);

    const result = await filterUsers(nullFilter);

    expect(mockQueryRawUnsafe).toHaveBeenCalledWith(
      "SELECT * FROM users WHERE 1=1"
    );
    expect(result).toEqual([]);
  });

  it('should handle integer boundary values', async () => {
    const edgeCaseFilter = { role: 'user', status: 'active', ageMin: -1, ageMax: Number.MAX_SAFE_INTEGER };
    mockQueryRawUnsafe.mockResolvedValue([]);

    const result = await filterUsers(edgeCaseFilter);

    expect(mockQueryRawUnsafe).toHaveBeenCalledWith(
      "SELECT * FROM users WHERE 1=1 AND role = 'user' AND status = 'active' AND age >= -1 AND age <= 9007199254740991"
    );
    expect(result).toEqual([]);
  });
});

// --- search (line 52) ---
import { search } from './typescript-prisma';
import { prisma } from './prisma-client';

jest.mock('./prisma-client');

describe('search function tests', () => {
  const mockPrismaResponse = [{ id: 1, name: 'John Doe' }];
  
  beforeEach(() => {
    (prisma.$queryRawUnsafe as jest.Mock).mockClear();
  });
  
  test('happy path: valid inputs', async () => {
    const params = { field: 'name', operator: '=', value: 'John Doe' };
    (prisma.$queryRawUnsafe as jest.Mock).mockResolvedValue(mockPrismaResponse);
    const result = await search(params);
    expect(result).toEqual(mockPrismaResponse);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith("SELECT * FROM users WHERE name = 'John Doe'");
  });
  
  test('SQL injection: malicious payload', async () => {
    const params = { field: 'name', operator: '=', value: "'; DROP TABLE users; --" };
    (prisma.$queryRawUnsafe as jest.Mock).mockResolvedValue(mockPrismaResponse);
    await search(params);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith("SELECT * FROM users WHERE name = ''; DROP TABLE users; --'");
  });
  
  test('Path traversal attack', async () => {
    const params = { field: 'file', operator: '=', value: '../../../etc/passwd' };
    (prisma.$queryRawUnsafe as jest.Mock).mockResolvedValue(mockPrismaResponse);
    await search(params);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith("SELECT * FROM users WHERE file = '../../../etc/passwd'");
  });
  
  test('oversized input', async () => {
    const params = { field: 'name', operator: '=', value: 'A'.repeat(10000) };
    (prisma.$queryRawUnsafe as jest.Mock).mockResolvedValue(mockPrismaResponse);
    await search(params);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(`SELECT * FROM users WHERE name = '${'A'.repeat(10000)}'`);
  });
  
  test('integer boundary values', async () => {
    const params = { field: 'id', operator: '=', value: '-1' };
    (prisma.$queryRawUnsafe as jest.Mock).mockResolvedValue(mockPrismaResponse);
    await search(params);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith("SELECT * FROM users WHERE id = '-1'");
  });
  
  test('null input', async () => {
    const params = { field: 'name', operator: '=', value: null };
    (prisma.$queryRawUnsafe as jest.Mock).mockResolvedValue(mockPrismaResponse);
    await search(params);
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith("SELECT * FROM users WHERE name = 'null'");
  });
});

// --- getUsersByDepartment (line 59) ---
import { getUsersByDepartment } from './typescript-prisma';
import prisma from '@prisma/client';
import { jest } from '@jest/globals';

jest.mock('@prisma/client', () => ({
  PrismaClient: jest.fn().mockImplementation(() => ({
    $queryRawUnsafe: jest.fn(),
  }))
}));

const mockPrisma = new prisma.PrismaClient();

describe('getUsersByDepartment', () => {
  const department = 'Engineering';
  const limit = 10;

  beforeAll(() => {
    jest.clearAllMocks();
  });

  it('should return users by department successfully', async () => {
    const mockResponse = [{ id: 1, name: 'John Doe', department }];
    mockPrisma.$queryRawUnsafe.mockResolvedValue(mockResponse);

    const result = await getUsersByDepartment(department, limit);
    expect(result).toEqual(mockResponse);
    expect(mockPrisma.$queryRawUnsafe).toHaveBeenCalledWith(`
      SELECT * FROM users
      WHERE department = '${department}'
      LIMIT ${limit}
    `);
  });

  it('should handle SQL injection payloads', async () => {
    const maliciousInput = "'; DROP TABLE users; --";
    mockPrisma.$queryRawUnsafe.mockResolvedValue([]);

    const result = await getUsersByDepartment(maliciousInput, limit);
    expect(result).toEqual([]);
    expect(mockPrisma.$queryRawUnsafe).toHaveBeenCalledWith(`
      SELECT * FROM users
      WHERE department = '${maliciousInput}'
      LIMIT ${limit}
    `);
  });

  it('should handle path traversal strings', async () => {
    const pathTraversal = '../../etc/passwd';
    mockPrisma.$queryRawUnsafe.mockResolvedValue([]);

    const result = await getUsersByDepartment(pathTraversal, limit);
    expect(result).toEqual([]);
    expect(mockPrisma.$queryRawUnsafe).toHaveBeenCalledWith(`
      SELECT * FROM users
      WHERE department = '${pathTraversal}'
      LIMIT ${limit}
    `);
  });

  it('should handle oversized inputs', async () => {
    const oversizedString = 'A'.repeat(10000);
    mockPrisma.$queryRawUnsafe.mockResolvedValue([]);

    const result = await getUsersByDepartment(oversizedString, limit);
    expect(result).toEqual([]);
    expect(mockPrisma.$queryRawUnsafe).toHaveBeenCalledWith(`
      SELECT * FROM users
      WHERE department = '${oversizedString}'
      LIMIT ${limit}
    `);
  });

  it('should handle integer boundary values', async () => {
    mockPrisma.$queryRawUnsafe.mockResolvedValue([]);

    const resultZero = await getUsersByDepartment(department, 0);
    expect(resultZero).toEqual([]);
    expect(mockPrisma.$queryRawUnsafe).toHaveBeenCalledWith(`
      SELECT * FROM users
      WHERE department = '${department}'
      LIMIT 0
    `);

    const resultNegative = await getUsersByDepartment(department, -1);
    expect(resultNegative).toEqual([]);
    expect(mockPrisma.$queryRawUnsafe).toHaveBeenCalledWith(`
      SELECT * FROM users
      WHERE department = '${department}'
      LIMIT -1
    `);

    const resultMaxInt = await getUsersByDepartment(department, Number.MAX_SAFE_INTEGER);
    expect(resultMaxInt).toEqual([]);
    expect(mockPrisma.$queryRawUnsafe).toHaveBeenCalledWith(`
      SELECT * FROM users
      WHERE department = '${department}'
      LIMIT ${Number.MAX_SAFE_INTEGER}
    `);
  });
});

// --- executeQuery (line 75) ---
import { executeQuery } from './typescript-prisma';
import { prisma } from '@prisma/client';

jest.mock('@prisma/client', () => ({
  prisma: {
    $queryRawUnsafe: jest.fn(),
  },
}));

describe('executeQuery', () => {
  afterEach(() => {
    jest.clearAllMocks();
  });

  test('should execute valid query with correct parameters', async () => {
    const builder = {
      select: ['id', 'name'],
      from: 'users',
      where: { id: 1 },
      orderBy: { field: 'name', direction: 'ASC' },
    };

    (prisma.$queryRawUnsafe as jest.Mock).mockResolvedValue([{ id: 1, name: 'John Doe' }]);

    const result = await executeQuery(builder);

    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(\`SELECT id, name FROM users WHERE id = '1' ORDER BY name ASC\`);
    expect(result).toEqual([{ id: 1, name: 'John Doe' }]);
  });

  test('should handle SQL injection payload', async () => {
    const builder = {
      select: ['*'],
      from: 'users',
      where: { id: '1; DROP TABLE users;' },
    };

    await expect(executeQuery(builder)).resolves.not.toThrow();
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(\`SELECT * FROM users WHERE id = '1; DROP TABLE users;'\`);
  });

  test('should handle path traversal attack', async () => {
    const builder = {
      select: ['*'],
      from: '../etc/passwd',
    };

    await expect(executeQuery(builder)).resolves.not.toThrow();
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(\`SELECT * FROM ../etc/passwd\`);
  });

  test('should handle oversized input', async () => {
    const oversizedString = 'a'.repeat(10000);
    const builder = {
      select: ['*'],
      from: 'users',
      where: { name: oversizedString },
    };

    await expect(executeQuery(builder)).resolves.not.toThrow();
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(\`SELECT * FROM users WHERE name = '${oversizedString}'\`);
  });

  test('should handle null input for where clause', async () => {
    const builder = {
      select: ['*'],
      from: 'users',
      where: { id: null },
    };

    await expect(executeQuery(builder)).resolves.not.toThrow();
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(\`SELECT * FROM users WHERE id = 'null'\`);
  });

  test('should handle boundary integer values', async () => {
    const builder = {
      select: ['*'],
      from: 'users',
      where: { id: Number.MAX_SAFE_INTEGER },
    };

    await expect(executeQuery(builder)).resolves.not.toThrow();
    expect(prisma.$queryRawUnsafe).toHaveBeenCalledWith(\`SELECT * FROM users WHERE id = '${Number.MAX_SAFE_INTEGER}'\`);
  });
});

// --- constructor (line 94) ---
import { MyClass } from './typescript-prisma';

jest.mock('./database', () => ({
    query: jest.fn(),
}));

describe('MyClass Tests', () => {
    let instance: MyClass;

    beforeEach(() => {
        instance = new MyClass('test_table');
    });

    afterEach(() => {
        jest.clearAllMocks();
    });

    test('happy path: valid table name', () => {
        expect(instance).toBeInstanceOf(MyClass);
    });

    test('SQL injection payload - should not execute', () => {
        const sqlInjectionPayload = "'; DROP TABLE users; --";
        instance = new MyClass(sqlInjectionPayload);
        expect(instance).toBeInstanceOf(MyClass);
    });

    test('path traversal payload - should not navigate outside allowed paths', () => {
        const pathTraversalPayload = "../../../etc/passwd";
        instance = new MyClass(pathTraversalPayload);
        expect(instance).toBeInstanceOf(MyClass);
    });

    test('oversized input - should handle large lengths', () => {
        const oversizedInput = 'a'.repeat(5000);
        instance = new MyClass(oversizedInput);
        expect(instance).toBeInstanceOf(MyClass);
    });

    test('null input - should throw an error', () => {
        expect(() => new MyClass(null)).toThrow(TypeError);
    });

    test('integer boundary values - should handle 0', () => {
        const boundaryInputZero = 0;
        instance = new MyClass(boundaryInputZero.toString());
        expect(instance).toBeInstanceOf(MyClass);
    });

    test('integer boundary values - should handle -1', () => {
        const boundaryInputMinusOne = -1;
        instance = new MyClass(boundaryInputMinusOne.toString());
        expect(instance).toBeInstanceOf(MyClass);
    });

    test('integer boundary values - should handle MAX_INT', () => {
        const maxInt = Number.MAX_SAFE_INTEGER;
        instance = new MyClass(maxInt.toString());
        expect(instance).toBeInstanceOf(MyClass);
    });
});

// --- findByField (line 96) ---
import { prisma } from './path/to/prismaClient';
import { findByField } from './path/to/yourFunction';

jest.mock('./path/to/prismaClient');

describe('findByField', () => {
  const tableName = 'testTable';
  beforeAll(() => {
    (findByField as jest.Mock).mockImplementation(async (fieldName, value) => {
      return Promise.resolve([{ id: 1, fieldName, value }]);
    });
  });

  it('should return expected results for valid inputs', async () => {
    const result = await findByField('name', 'John Doe');
    expect(result).toEqual([{ id: 1, fieldName: 'name', value: 'John Doe' }]);
  });

  it('should handle SQL injection attempts', async () => {
    const maliciousInput = "' OR '1'='1";
    const result = await findByField('name', maliciousInput);
    expect(result).not.toContainEqual(expect.objectContaining({fieldName: 'name', value: maliciousInput}));
  });

  it('should handle path traversal strings', async () => {
    const traversalInput = '../etc/passwd';
    const result = await findByField('filePath', traversalInput);
    expect(result).not.toContainEqual(expect.objectContaining({fieldName: 'filePath', value: traversalInput}));
  });

  it('should reject oversized input', async () => {
    const oversizedInput = 'x'.repeat(10000);
    await expect(findByField('name', oversizedInput)).rejects.toThrow();
  });

  it('should handle null input', async () => {
    await expect(findByField('name', null)).rejects.toThrow();
  });

  it('should handle integer boundary values', async () => {
    await expect(findByField('age', 0)).resolves.not.toThrow();
    await expect(findByField('age', -1)).resolves.not.toThrow();
    await expect(findByField('age', Number.MAX_SAFE_INTEGER)).resolves.not.toThrow();
  });
});

// --- deleteWhere (line 101) ---
import { deleteWhere } from './typescript-prisma';
import { PrismaClient } from '@prisma/client';

jest.mock('@prisma/client');
const prisma = new PrismaClient();

describe('deleteWhere', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('should delete records when valid condition is provided', async () => {
    const condition = 'id = 1';
    (prisma.$executeRawUnsafe as jest.Mock).mockResolvedValue(1);
    const result = await deleteWhere(condition);
    expect(result).toBe(1);
    expect(prisma.$executeRawUnsafe).toHaveBeenCalledWith(`DELETE FROM tableName WHERE ${condition}`);
  });

  it('should handle SQL injection payloads', async () => {
    const condition = "id = 1; DROP TABLE users; --";
    (prisma.$executeRawUnsafe as jest.Mock).mockResolvedValue(0);
    const result = await deleteWhere(condition);
    expect(result).toBe(0);
    expect(prisma.$executeRawUnsafe).toHaveBeenCalledWith(`DELETE FROM tableName WHERE ${condition}`);
  });

  it('should handle path traversal strings', async () => {
    const condition = `id = 1 OR path = '../../etc/passwd'`;
    (prisma.$executeRawUnsafe as jest.Mock).mockResolvedValue(0);
    const result = await deleteWhere(condition);
    expect(result).toBe(0);
    expect(prisma.$executeRawUnsafe).toHaveBeenCalledWith(`DELETE FROM tableName WHERE ${condition}`);
  });

  it('should handle oversized input', async () => {
    const condition = 'a'.repeat(10000);
    (prisma.$executeRawUnsafe as jest.Mock).mockResolvedValue(0);
    const result = await deleteWhere(condition);
    expect(result).toBe(0);
    expect(prisma.$executeRawUnsafe).toHaveBeenCalledWith(`DELETE FROM tableName WHERE ${condition}`);
  });

  it('should handle null input', async () => {
    const condition = null;
    await expect(deleteWhere(condition)).rejects.toThrow();
  });

  it('should handle integer boundary values', async () => {
    const conditions = ["id = 0", "id = -1", "id = 2147483647"];
    for (const condition of conditions) {
      (prisma.$executeRawUnsafe as jest.Mock).mockResolvedValue(1);
      const result = await deleteWhere(condition);
      expect(result).toBe(1);
      expect(prisma.$executeRawUnsafe).toHaveBeenCalledWith(`DELETE FROM tableName WHERE ${condition}`);
    }
  });
});

